# Base Image
FROM python:3.10-slim-bullseye
#set working director
RUN mkdir /app
RUN chmod 775 -R /app/


WORKDIR /app

COPY requirements.txt requirements.txt


EXPOSE 8000

# runs the production server

COPY manage.py /musicfy/
COPY .env /musicfy/.env

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV HEALTHCHECK_PORT 81
ENV LC_ALL pt_BR.UTF-8
ENV LANG pt_BR.UTF-8
ENV TZ=America/Sao_Paulo


RUN apt-get update && apt-get install -y --no-install-recommends \
    pkg-config \
    apt-utils \
    locales \
    tzdata \
    git \
    iputils-ping \
    python3-setuptools \
    python3-pip \
    python3-dev \
    python3-venv \
    gcc \
    vim \
    libssl-dev \
    procps \
    supervisor \
    default-libmysqlclient-dev \ 
    build-essential \
    cargo \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*



RUN echo "pt_BR.UTF-8 UTF-8" >> /etc/locale.gen && locale-gen
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN locale-gen pt_BR.UTF-8   

RUN python3 -m pip install --upgrade pip==24.0
RUN python3 -m pip install -r requirements.txt
RUN git config --global --add safe.directory /app